# Generated by Django 4.2.28 on 2026-03-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RescueTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("team", models.CharField(max_length=140)),
                ("location", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("alta", "Alta"),
                            ("media", "Média"),
                            ("baixa", "Baixa"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberto", "Aberto"),
                            ("em_acao", "Em ação"),
                            ("concluido", "Concluído"),
                        ],
                        default="aberto",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="rescue_ops__status_112e89_idx",
                    ),
                    models.Index(
                        fields=["priority", "-created_at"],
                        name="rescue_ops__priorit_c3b813_idx",
                    ),
                ],
            },
        ),
    ]
