FROM oven/bun:1.2.14-alpine
WORKDIR /app
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile
COPY . .
ENV VITE_API_BASE_URL="http://localhost:8001"
EXPOSE 8000
CMD ["bun", "x", "vite", "--host", "0.0.0.0", "--port", "8000"]
