// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SosLocation.Infrastructure.Persistence;

#nullable disable

namespace SosLocation.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SosDbContext))]
    [Migration("20260715212830_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SosLocation.Domain.Catalog.Dataset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Attribution")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attribution");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DatasetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dataset_type");

                    b.Property<string>("License")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("license");

                    b.Property<string>("LicenseUri")
                        .HasColumnType("text")
                        .HasColumnName("license_uri");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("SourceUri")
                        .HasColumnType("text")
                        .HasColumnName("source_uri");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("datasets", (string)null);
                });

            modelBuilder.Entity("SosLocation.Domain.Catalog.DatasetVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<string>("Checksum")
                        .HasColumnType("text")
                        .HasColumnName("checksum");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid")
                        .HasColumnName("dataset_id");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("StorageKey")
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<DateTimeOffset?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("dataset_versions", (string)null);
                });

            modelBuilder.Entity("SosLocation.Domain.Cities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Geometry>("Boundary")
                        .HasColumnType("geometry")
                        .HasColumnName("boundary");

                    b.Property<Point>("Centroid")
                        .HasColumnType("geometry")
                        .HasColumnName("centroid");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("region");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Boundary");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "gist");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("SosLocation.Domain.Cities.CityRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("QualityLevel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("quality_level");

                    b.Property<string>("ReconstructionProfile")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reconstruction_profile");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("revision_number");

                    b.Property<string>("SourceSummary")
                        .HasColumnType("jsonb")
                        .HasColumnName("source_summary");

                    b.Property<Geometry>("SpatialCoverage")
                        .HasColumnType("geometry")
                        .HasColumnName("spatial_coverage");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("SpatialCoverage");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SpatialCoverage"), "gist");

                    b.HasIndex("Status");

                    b.HasIndex("CityId", "RevisionNumber")
                        .IsUnique();

                    b.ToTable("city_revisions", (string)null);
                });

            modelBuilder.Entity("SosLocation.Domain.Features.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("BuildingLevels")
                        .HasColumnType("integer")
                        .HasColumnName("building_levels");

                    b.Property<string>("BuildingType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("building_type");

                    b.Property<Point>("Centroid")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("centroid");

                    b.Property<Guid>("CityRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_revision_id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_id");

                    b.Property<Geometry>("Footprint")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("footprint");

                    b.Property<double>("GroundElevationMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("ground_elevation_m");

                    b.Property<double>("HeightMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("height_m");

                    b.Property<string>("HeightSource")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("height_source");

                    b.Property<double>("MinHeightMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("min_height_m");

                    b.Property<int?>("RoofLevels")
                        .HasColumnType("integer")
                        .HasColumnName("roof_levels");

                    b.Property<string>("RoofShape")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("roof_shape");

                    b.Property<Guid?>("SourceDatasetVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_dataset_version_id");

                    b.Property<string>("Tags")
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.HasKey("Id");

                    b.HasIndex("CityRevisionId");

                    b.HasIndex("Footprint");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Footprint"), "gist");

                    b.HasIndex("CityRevisionId", "ExternalId")
                        .IsUnique();

                    b.ToTable("buildings", (string)null);
                });

            modelBuilder.Entity("SosLocation.Domain.Features.LandUseArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CityRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_revision_id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_id");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("geometry");

                    b.Property<string>("LandUseType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("land_use_type");

                    b.Property<Guid?>("SourceDatasetVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_dataset_version_id");

                    b.Property<string>("Tags")
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.HasKey("Id");

                    b.HasIndex("CityRevisionId");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("CityRevisionId", "ExternalId")
                        .IsUnique();

                    b.ToTable("land_use_areas", (string)null);
                });

            modelBuilder.Entity("SosLocation.Domain.Features.Road", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CityRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_revision_id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_id");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("geometry");

                    b.Property<bool>("IsBridge")
                        .HasColumnType("boolean")
                        .HasColumnName("is_bridge");

                    b.Property<bool>("IsTunnel")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tunnel");

                    b.Property<int?>("Lanes")
                        .HasColumnType("integer")
                        .HasColumnName("lanes");

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<string>("RoadClass")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("road_class");

                    b.Property<Guid?>("SourceDatasetVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_dataset_version_id");

                    b.Property<string>("Tags")
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<double?>("WidthMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("width_m");

                    b.HasKey("Id");

                    b.HasIndex("CityRevisionId");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("CityRevisionId", "ExternalId")
                        .IsUnique();

                    b.ToTable("roads", (string)null);
                });

            modelBuilder.Entity("SosLocation.Domain.Features.WaterFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CityRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_revision_id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_id");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("geometry");

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<Guid?>("SourceDatasetVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_dataset_version_id");

                    b.Property<string>("Tags")
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<string>("WaterType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("water_type");

                    b.HasKey("Id");

                    b.HasIndex("CityRevisionId");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("CityRevisionId", "ExternalId")
                        .IsUnique();

                    b.ToTable("water_features", (string)null);
                });

            modelBuilder.Entity("SosLocation.Domain.Jobs.ImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<Guid?>("CityRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_revision_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentStage")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("current_stage");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("job_type");

                    b.Property<int>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("request");

                    b.Property<string>("StageMessage")
                        .HasColumnType("text")
                        .HasColumnName("stage_message");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("WorkerId")
                        .HasColumnType("text")
                        .HasColumnName("worker_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("import_jobs", (string)null);
                });

            modelBuilder.Entity("SosLocation.Domain.Jobs.ProcessingIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("FeatureId")
                        .HasColumnType("text")
                        .HasColumnName("feature_id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("severity");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("processing_issues", (string)null);
                });

            modelBuilder.Entity("SosLocation.Domain.Catalog.DatasetVersion", b =>
                {
                    b.HasOne("SosLocation.Domain.Catalog.Dataset", null)
                        .WithMany()
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SosLocation.Domain.Cities.CityRevision", b =>
                {
                    b.HasOne("SosLocation.Domain.Cities.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SosLocation.Domain.Features.Building", b =>
                {
                    b.HasOne("SosLocation.Domain.Cities.CityRevision", null)
                        .WithMany()
                        .HasForeignKey("CityRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SosLocation.Domain.Features.LandUseArea", b =>
                {
                    b.HasOne("SosLocation.Domain.Cities.CityRevision", null)
                        .WithMany()
                        .HasForeignKey("CityRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SosLocation.Domain.Features.Road", b =>
                {
                    b.HasOne("SosLocation.Domain.Cities.CityRevision", null)
                        .WithMany()
                        .HasForeignKey("CityRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SosLocation.Domain.Features.WaterFeature", b =>
                {
                    b.HasOne("SosLocation.Domain.Cities.CityRevision", null)
                        .WithMany()
                        .HasForeignKey("CityRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SosLocation.Domain.Jobs.ProcessingIssue", b =>
                {
                    b.HasOne("SosLocation.Domain.Jobs.ImportJob", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
