import { useMemo } from 'react';
import MarkerClusterGroup from 'react-leaflet-cluster';
import { MapContainer, TileLayer } from 'react-leaflet';
import { Modal } from '../components/ui/Modal';
import { QuickActions } from '../components/ui/QuickActions';


import { MapInteractions, MapListener } from '../components/map/MapInteractions';
import { MemoizedEventMarker } from '../components/map/EventMarker';
import { LiveOpsPanel } from '../components/map/LiveOpsPanel';
import { CursorCoordinates } from '../components/map/CursorCoordinates';
import { MapContextMenu } from '../components/map/MapContextMenu';

import { useSOSPageData } from '../hooks/useSOSPageData';
import { useSOSPageController } from '../hooks/useSOSPageController';
import { SOSHeaderHUD } from '../components/ui/SOSHeaderHUD';
import { AlertSidebar } from '../components/ui/AlertSidebar';
import { MissionsPanel } from '../components/gamification/MissionsPanel';
import { GamificationHud } from '../components/gamification/GamificationHud';
import { SituationIntelPanel } from '../components/ui/SituationIntelPanel';
import { TacticalOpsForm } from '../components/ui/TacticalOpsForm';
import {
  Box,
  VStack,
  Center,
  Spinner,
} from '@chakra-ui/react';
import { TacticalText } from '../components/atoms/TacticalText';

/**
 * SOS War Room / Dashboard
 * The core operational environment. Refactored for Clean Architecture
 * and unified Tactical Design System.
 */
export function SOSPage() {
  const {
    events, domainEvents, alerts, mapAnnotations, opsSnapshot,
    country, setCountry,
    currentDisplayEvents,
    saveOps, sidebarAlerts
  } = useSOSPageData();

  const { states, actions } = useSOSPageController(saveOps);

  const selectedEvent = useMemo(() => {
    if (!states.hoveredId) return null;
    return (events as any[]).find(e => `${e.provider}-${e.provider_event_id}` === states.hoveredId) ||
      domainEvents.find(e => e.id === states.hoveredId) ||
      (alerts as any[]).find(a => `alert-${a.id}` === states.hoveredId) ||
      (mapAnnotations as any[]).find(m => `ann-${m.id}` === states.hoveredId) ||
      (sidebarAlerts as any[]).find((a: any) => a.id === states.hoveredId);
  }, [states.hoveredId, events, domainEvents, alerts, mapAnnotations, sidebarAlerts]);

  return (
    <Box h="100vh" w="100vw" position="relative" overflow="hidden" bg="sos.dark">
      {/* Ambient Tactical Overlays */}
      <Box position="absolute" inset={0} className="ambient-glow" zIndex={1} />
      <Box position="absolute" inset={0} className="scanline-overlay" zIndex={100} />
      <Box position="absolute" inset={0} className="vignette-overlay" zIndex={101} />

      {/* Floating Header */}
      <SOSHeaderHUD
        country={country}
        setCountry={setCountry}
        onReset={actions.resetMap}
        activeTool={states.tool}
        setTool={actions.setTool}
        onSearchSelect={(lat, lon) => {
          actions.setMapCenter([lat, lon]);
          actions.setMapZoom(14);
        }}
        stats={{
          activeTeams: opsSnapshot?.kpis?.activeTeams ?? '--',
          criticalAlerts: opsSnapshot?.kpis?.criticalAlerts ?? '--',
          supplies: opsSnapshot?.kpis?.suppliesInTransit ?? '--',
          missingPersons: opsSnapshot?.layers?.missingPersons?.length ?? '0'
        }}
      />

      <Box position="absolute" top="112px" left={6} bottom={6} zIndex={40}>
        <AlertSidebar
          alerts={sidebarAlerts.map((a: any) => ({
            ...a,
            description: a.description || `Tactical alert generated by ${a.source || 'system'} telemetry`,
            lat: a.lat,
            lon: a.lon
          }))}
          kpis={{
            criticalAlerts: opsSnapshot?.kpis?.criticalAlerts || 0,
            activeTeams: opsSnapshot?.kpis?.activeTeams || 0,
            missingPersons: opsSnapshot?.layers?.missingPersons?.length || 0
          }}
          onAlertClick={(alert) => {
            if (alert.lat && alert.lon) {
              actions.setMapCenter([alert.lat, alert.lon]);
              actions.setMapZoom(15);
            }
          }}
        />
      </Box>

      {/* Gamification Feed (Right) */}
      <VStack 
        position="absolute" 
        top="112px" 
        right={6} 
        bottom={6} 
        zIndex={40} 
        display={{ base: 'none', '2xl': 'flex' }} 
        spacing={6} 
        align="stretch"
        w="340px"
      >
         <GamificationHud
           xp={3420}
           level={42}
           rank="Sentinel III"
           nextLevelXp={5000}
           w="full"
         />
         <Box flex={1} overflow="hidden">
           <MissionsPanel />
         </Box>
      </VStack>

      {/* Quick Action Bar (Bottom) */}
      <Box position="absolute" bottom={8} left="50%" transform="translateX(-50%)" zIndex={110}>
        <QuickActions onToggleLiveOps={() => actions.setLiveOpsPanelOpen(!states.liveOpsPanelOpen)} onAction={actions.handleQuickAction} />
      </Box>

      {states.intelPanelOpen && selectedEvent && (
        <SituationIntelPanel 
          event={selectedEvent} 
          onClose={() => {
            actions.setIntelPanelOpen(false);
            actions.setHoveredId(null);
          }} 
        />
      )}

      {states.liveOpsPanelOpen && (
        <LiveOpsPanel onClose={() => actions.setLiveOpsPanelOpen(false)} />
      )}

      {/* Primary Map Foundation */}
      <Box position="absolute" inset={0} zIndex={0}>
        {states.mapCenter && states.mapCenter[0] !== undefined ? (
          <MapContainer center={states.mapCenter} zoom={states.mapZoom} zoomControl={false} style={{ height: '100%', width: '100%', filter: 'contrast(1.1) brightness(0.9)' }}>
            <TileLayer attribution='&copy; CARTO' url='https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png' />
            <MapListener onMove={(c, z) => { actions.setMapCenter(c); actions.setMapZoom(z); }} />
            <MapInteractions
              tool={states.tool}
              onPickPoint={(lat, lon) => {
                actions.setLastClickedCoords([lat, lon]);
                actions.setOpenOpsModal(true);
              }}
              onHover={actions.handleMapHover}
              areaDraft={states.areaDraft}
              setAreaDraft={actions.setAreaDraft}
              spatialFilter={states.spatialFilter}
              setSpatialFilter={actions.setSpatialFilter}
              onFilterComplete={() => { }}
              onSnapshotComplete={() => { }}
              onContextMenu={(x, y, lat, lon) => actions.setContextMenu({ x, y, lat, lon })}
              show3D={false}
            />
            <MarkerClusterGroup chunkedLoading maxClusterRadius={50}>
              {(currentDisplayEvents || []).map((e) => {
                if (!e) return null;
                return (
                  <MemoizedEventMarker 
                    key={e.id || `${e.provider}-${e.provider_event_id}`} 
                    e={e} 
                    isHovered={states.hoveredId === (e.id || `${e.provider}-${e.provider_event_id}`)} 
                    onHover={actions.handleMarkerHover} 
                    onUnhover={actions.handleMarkerUnhover} 
                  />
                );
              })}
            </MarkerClusterGroup>
          </MapContainer>
        ) : (
          <Center h="full" bg="sos.dark" zIndex={2}>
            <VStack spacing={6}>
              <Spinner 
                size="xl" 
                thickness="4px" 
                speed="0.8s" 
                color="sos.blue.500" 
                emptyColor="whiteAlpha.100" 
              />
              <VStack spacing={1}>
                <TacticalText variant="heading" fontSize="lg" color="white">
                  INITIALIZING GUARDIAN TERMINAL
                </TacticalText>
                <TacticalText variant="mono" fontSize="xs" color="sos.blue.400" className="animate-pulse">
                  ESTABLISHING SECURE SATELLITE UPLINK...
                </TacticalText>
              </VStack>
            </VStack>
          </Center>
        )}
      </Box>


      {/* Tactical Registration Modal */}
      <Modal title="CADASTRO TÁTICO DE CAMPO" open={states.openOpsModal} onClose={() => actions.setOpenOpsModal(false)}>
        <TacticalOpsForm 
          opsForm={states.opsForm} 
          setOpsForm={actions.setOpsForm} 
          onSave={actions.executeSaveOps} 
        />
      </Modal>

      <CursorCoordinates coords={states.cursorCoords} />
      
      {states.contextMenu && (
        <MapContextMenu
          x={states.contextMenu.x}
          y={states.contextMenu.y}
          lat={states.contextMenu.lat}
          lng={states.contextMenu.lon}
          onClose={() => actions.setContextMenu(null)}
          onMarkRiskArea={(lat: number, lng: number) => {
            actions.setLastClickedCoords([lat, lng]);
            actions.setOpsForm(prev => ({ ...prev, recordType: 'risk_area' }));
            actions.setOpenOpsModal(true);
          }}
        />
      )}
    </Box>
  );
}
