from django.urls import path

from apps.api.views import (
    attention_alerts,
    calculatecoordinate,
    cfd_ideas,
    climate_integrations,
    collapse_reports,
    health_check,
    hotspots,
    identify_victim,
    location_flow_simulation,
    location_flow_simulation_stream,
    map_annotations,
    missing_people_csv,
    missing_persons,
    news_updates,
    operations_snapshot,
    push_register,
    report_info,
    rescue_groups,
    rescue_support,
    risk_areas,
    searched_areas,
    splat_convert,
    supply_logistics,
    support_points,
    terrain_context,
    unified_easy_simulation,
)
from apps.api.views_auth import (
    auth_login,
    auth_logout,
    auth_me,
    auth_register,
    google_oauth2_login_view,
    keycloak_sso_login_view,
    login_view,
    logout_view,
    session_view,
)
from apps.api.views_disasters import disasters_by_country, disasters_crawl_trigger, disasters_events, disasters_timeseries
from apps.api.views_integrations import (
    alerts as alerts_feed,
    disaster_intelligence,
    satellite_goes_recent,
    satellite_landsat_catalog,
    satellite_layers,
    satellite_stac_search,
    transparency_search,
    transparency_summary,
    transparency_transfers,
    ibge_municipios,
    weather_archive,
    weather_forecast,
    weather_nowcast,
)
from apps.api.views_modules import (
    incident_detail,
    incidents_collection,
    public_incidents,
    public_latest_snapshot,
    public_search_areas,
    public_support_summary,
    rescue_assignments,
    rescue_search_area_update,
    rescue_search_areas,
    support_campaigns,
    support_donations,
    support_expenses,
)
from apps.api.views_risk import risk_assessment, risk_pipeline_sync
from apps.api.views_sync import sync_events, list_domain_events
from apps.api.views_hubs import hub_register, hub_list

app_name = 'api'

urlpatterns = [
    path('health', health_check, name='health_check'),

    path('incidents', incidents_collection, name='incidents_collection'),
    path('incidents/<int:incident_id>', incident_detail, name='incident_detail'),
    path('incidents/<int:incident_id>/support/campaigns', support_campaigns, name='support_campaigns'),
    path('incidents/<int:incident_id>/support/donations/money', support_donations, name='support_donations'),
    path('incidents/<int:incident_id>/support/expenses', support_expenses, name='support_expenses'),
    path('incidents/<int:incident_id>/rescue/search-areas', rescue_search_areas, name='rescue_search_areas'),
    path('incidents/<int:incident_id>/rescue/search-areas/<int:area_id>', rescue_search_area_update, name='rescue_search_area_update'),
    path('incidents/<int:incident_id>/rescue/assignments', rescue_assignments, name='rescue_assignments'),
    path('public/incidents', public_incidents, name='public_incidents'),
    path('public/incidents/<int:incident_id>/snapshot/latest', public_latest_snapshot, name='public_latest_snapshot'),
    path('public/incidents/<int:incident_id>/support/summary', public_support_summary, name='public_support_summary'),
    path('public/incidents/<int:incident_id>/rescue/search-areas', public_search_areas, name='public_search_areas'),

    path('auth/register', auth_register, name='auth_register'),
    path('auth/login', auth_login, name='auth_login'),
    path('auth/me', auth_me, name='auth_me'),
    path('auth/logout', auth_logout, name='auth_logout'),
    path('auth/session-login', login_view, name='auth_session_login'),
    path('auth/session-logout', logout_view, name='auth_session_logout'),
    path('auth/session', session_view, name='auth_session'),
    path('auth/google', google_oauth2_login_view, name='auth_google'),
    path('auth/keycloak', keycloak_sso_login_view, name='auth_keycloak'),

    path('disasters/events', disasters_events, name='disasters_events'),
    path('disasters/stats/by-country', disasters_by_country, name='disasters_by_country'),
    path('disasters/stats/by-country', disasters_by_country, name='disasters_stats_by_country'),
    path('disasters/stats/timeseries', disasters_timeseries, name='disasters_timeseries'),
    path('disasters/stats/timeseries', disasters_timeseries, name='disasters_stats_timeseries'),
    path('disasters/crawl', disasters_crawl_trigger, name='disasters_crawl_trigger'),

    path('calculate', calculatecoordinate, name='coordinate_calculate'),
    path('hotspots', hotspots, name='hotspots'),
    path('collapse-reports', collapse_reports, name='collapse_reports'),
    path('rescue-support', rescue_support, name='rescue_support'),
    path('climate/integrations', climate_integrations, name='climate_integrations'),
    path('location/flow-simulation', location_flow_simulation, name='location_flow_simulation'),
    path('location/flow-simulation/stream', location_flow_simulation_stream, name='location_flow_simulation_stream'),
    path('simulation/easy', unified_easy_simulation, name='unified_easy_simulation'),
    path('terrain/context', terrain_context, name='terrain_context'),
    path('searched-areas', searched_areas, name='searched_areas'),
    path('report-info', report_info, name='report_info'),
    path('missing-people.csv', missing_people_csv, name='missing_people_csv'),
    path('missing-persons', missing_persons, name='missing_persons'),
    path('news-updates', news_updates, name='news_updates'),
    path('identify-victim', identify_victim, name='identify_victim'),
    path('cfd/ideas', cfd_ideas, name='cfd_ideas'),
    path('splat/convert', splat_convert, name='splat_convert'),
    path('push/register', push_register, name='push_register'),
    path('attention-alerts', attention_alerts, name='attention_alerts'),
    path('operations/snapshot', operations_snapshot, name='operations_snapshot'),
    path('map-annotations', map_annotations, name='map_annotations'),
    path('support-points', support_points, name='support_points'),
    path('risk-areas', risk_areas, name='risk_areas'),
    path('rescue-groups', rescue_groups, name='rescue_groups'),
    path('supply-logistics', supply_logistics, name='supply_logistics'),
    path('risk/assessment', risk_assessment, name='risk_assessment'),
    path('risk/pipeline-sync', risk_pipeline_sync, name='risk_pipeline_sync'),
    path('weather/forecast', weather_forecast, name='weather_forecast'),
    path('weather', weather_nowcast, name='weather_nowcast'),
    path('integrations/weather/forecast', weather_forecast, name='integrations_weather_forecast'),
    path('weather/archive', weather_archive, name='weather_archive'),
    path('integrations/weather/archive', weather_archive, name='integrations_weather_history'),
    path('alerts', alerts_feed, name='alerts_feed'),
    path('integrations/alerts', alerts_feed, name='integrations_alerts'),
    path('alerts/intelligence', disaster_intelligence, name='disaster_intelligence'),
    path('transparency/transfers', transparency_transfers, name='transparency_transfers'),
    path('integrations/transparency/transfers', transparency_transfers, name='integrations_transparency_transfers'),
    path('transparency/search', transparency_search, name='transparency_search'),
    path('integrations/transparency/summary', transparency_summary, name='integrations_transparency_summary'),
    path('integrations/ibge/municipios', ibge_municipios, name='integrations_ibge_municipios'),
    path('satellite/layers', satellite_layers, name='satellite_layers'),
    path('integrations/satellite/layers', satellite_layers, name='integrations_satellite_layers'),
    path('integrations/satellite/landsat/catalog', satellite_landsat_catalog, name='integrations_satellite_landsat_catalog'),
    path('satellite/stac/search', satellite_stac_search, name='satellite_stac_search'),
    path('satellite/goes/recent', satellite_goes_recent, name='satellite_goes_recent'),
    path('sync', sync_events, name='sync_events'),
    path('events', list_domain_events, name='list_domain_events'),
    path('hubs', hub_list, name='hub_list'),
    path('hubs/register', hub_register, name='hub_register'),
]
